name: capstone
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - jupyter
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - notebook
  - pip
  - pip:
    - faker
    - openpyxl
